## Numpy
Numpy is a package for array processing

### Array
An Array is a multidimensional data structure.
#### Features
* Contains items of the same data type
* Whereas in list, it can store items of different data types
* Arrays are of fixed size and type that you define at creation. Cannot append new values like lists.
* Arrays are faster, take up less space and have more functionality than lists
* Multidimensional arrays can be created.

Solving environment: ...working... done

# All requested packages already installed.

Note: you may need to restart the kernel to use updated packages.



In [1]:
import numpy as np

In [9]:
my_list=[1,2,3,4,5,6]

In [10]:
my_arr=np.array(my_list)

In [4]:
my_arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_arr.shape

(6,)

In [12]:
new_arr=my_arr.reshape(2,3)

In [9]:
my_arr.shape

(6,)

In [10]:
my_arr

array([1, 2, 3, 4, 5, 6])

In [11]:
my_arr[2]

3

In [11]:
my_arr[0:4]

array([1, 2, 3, 4])

In [12]:
my_arr[0:2]=10
print(my_arr)

[10 10  3  4  5  6]


In [13]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
new_arr[1:,1:]

array([[5, 6]])

In [13]:
#Slicing an array - taking elements from specific range and move it to another variable

n_arr=my_arr[0:4]
print(n_arr)

[10 10  3  4]


#### Create multidimensional array

In [16]:
my_list1=[1,2,3,4,5,6]
my_list2=[2,4,6,8,10,12]
my_list3=[1,3,5,7,9,11]

arr1=np.array([my_list1,my_list2,my_list3])

In [17]:
print(arr1)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 1  3  5  7  9 11]]


In [18]:
arr1.shape

(3, 6)

In [19]:
arr1[0:2,0:3]

array([[1, 2, 3],
       [2, 4, 6]])

In [20]:
arr1[0:2,0:3]*2

array([[ 2,  4,  6],
       [ 4,  8, 12]])

In [21]:
arr1[:,2:]

array([[ 3,  4,  5,  6],
       [ 6,  8, 10, 12],
       [ 5,  7,  9, 11]])

In [22]:
my_arr[3:]=10

In [23]:
print(my_arr)

[ 1  2  3 10 10 10]


In [25]:
my_arr[my_arr<3]

array([1, 2])

### Create arrays 
Here are some functions used to create arrays
* np.empty(int n) - Generates empty 1-D array of size n
* np.ones(int n) - Creates a 1-D array of 1's of size n
* np.zeros(int n) - Creates a 1-D array of 0's of size n
* np.eye(int n) - Creates a 2-D array identity matrix of rows and columns of order n
* np.arange(int start, int stop, int step) - Generates array containing elements from start to stop with difference equal to step

#### empty() - creates 1-D array

In [3]:
print("An Empty array of size 3")
print(np.empty(3))

An Empty array of size 3
[6.89798700e-307 2.00270568e-307 1.46420397e-312]


#### np.ones() - creates 1D array of 1's

In [4]:
print("1D array of 1's")
print(np.ones(4))

1D array of 1's
[1. 1. 1. 1.]


#### np.zeros() - creates 1D array of 0's

In [5]:
print("1D array of 0's")
print(np.zeros(4))

1D array of 0's
[0. 0. 0. 0.]


#### eye() - 2D arrayof rows and columns

In [7]:
print("2D identity matrix")
print(np.eye(5))

2D identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### arange() creates one-dimensional array

In [36]:
arr3=np.arange(0,10)

In [37]:
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
arr3=np.arange(0,10,step=2)

In [39]:
print(arr3)

[0 2 4 6 8]


###### arange().reshape() creates multi-dimensional array

In [28]:
arr2=np.arange(0,6).reshape(2,3)

In [30]:
print(arr2)

[[0 1 2]
 [3 4 5]]


In [31]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [32]:
my_arr

array([ 1,  2,  3, 10, 10, 10])

In [40]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

##### Arithmetic operations

In [64]:
arr1<2

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [68]:
arr1[arr1<2]

array([1, 1])

In [65]:
arr1/2

array([[0.5, 1. , 1.5, 2. , 2.5, 3. ],
       [1. , 2. , 3. , 4. , 5. , 6. ],
       [0.5, 1.5, 2.5, 3.5, 4.5, 5.5]])

In [66]:
arr1%2

array([[1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [67]:
arr1+2

array([[ 3,  4,  5,  6,  7,  8],
       [ 4,  6,  8, 10, 12, 14],
       [ 3,  5,  7,  9, 11, 13]])

In [35]:
#Multiply the elements of 2 arrays
arr1*my_arr

array([[  1,   4,   9,  40,  50,  60],
       [  2,   8,  18,  80, 100, 120],
       [  1,   6,  15,  70,  90, 110]])

#### Copy and broadcasting

In [44]:
a1=np.array([1,2,3,4,5,6,7,8])

In [46]:
print(type(a1))

<class 'numpy.ndarray'>


In [49]:
a1[4:]=10

In [50]:
print(a1)

[ 1  2  3  4 10 10 10 10]


In [51]:
a2=a1

In [52]:
a2

array([ 1,  2,  3,  4, 10, 10, 10, 10])

In [53]:
a2[4:]=20

In [54]:
a2

array([ 1,  2,  3,  4, 20, 20, 20, 20])

In [55]:
a1

array([ 1,  2,  3,  4, 20, 20, 20, 20])

#### Whenever a numpy array is sliced into another variable, it doesnt create another array but only a reference to the original array is created.
#### So the changes made in the new array will also be reflected in the original array
#### Array is a reference type
#### Since both a1 and a2 references same memory, when you update a2, a1 gets updated too
#### So copy() function has to be explicitly called to create another copy in memory

In [57]:
a3=a1.copy()

In [58]:
a3

array([ 1,  2,  3,  4, 20, 20, 20, 20])

In [60]:
a3[4:]=100

In [61]:
a3

array([  1,   2,   3,   4, 100, 100, 100, 100])

In [62]:
a1

array([ 1,  2,  3,  4, 20, 20, 20, 20])

In [ ]:
#### Here copy() copies data from a1 to a3 but they both referene different memories

#### Transposing numpy arrays

In [16]:
## Creating 2D array
arr1 = np.arange(1,7,1).reshape(2,3)
print(arr1)

[[1 2 3]
 [4 5 6]]


In [18]:
print("transposed array")
print(arr1.transpose())

transposed array
[[1 4]
 [2 5]
 [3 6]]


#### More Numpy functions


In [19]:
arr2 = np.arange(1,40,4)
arr3 = np.arange(1,30,3)
print("1st array",arr2)
print("2nd array",arr3)

1st array [ 1  5  9 13 17 21 25 29 33 37]
2nd array [ 1  4  7 10 13 16 19 22 25 28]


In [21]:
print("The Exponent function")
print(np.exp(arr2))

The Exponent function
[2.71828183e+00 1.48413159e+02 8.10308393e+03 4.42413392e+05
 2.41549528e+07 1.31881573e+09 7.20048993e+10 3.93133430e+12
 2.14643580e+14 1.17191424e+16]


In [23]:
print("The Square function")
print(np.square(arr2))

The Square function
[   1   25   81  169  289  441  625  841 1089 1369]


In [24]:
print("The Sqrt function")
print(np.sqrt(arr2))

The Sqrt function
[1.         2.23606798 3.         3.60555128 4.12310563 4.58257569
 5.         5.38516481 5.74456265 6.08276253]


In [25]:
print("The Cuberoot function")
print(np.cbrt(arr2))

The Cuberoot function
[1.         1.70997595 2.08008382 2.35133469 2.57128159 2.75892418
 2.92401774 3.07231683 3.20753433 3.33222185]


In [26]:
print("Adding two arrays")
print(np.add(arr2,arr3))

Adding two arrays
[ 2  9 16 23 30 37 44 51 58 65]


In [28]:
print("Subtracting two arrays")
print(np.subtract(arr2,arr3))

Subtracting two arrays
[0 1 2 3 4 5 6 7 8 9]


### Numpy array processing

##### Where() function

In [32]:
arr4=np.array([10,20,30,40])
arr5=np.array([100,200,300,400])
print("Array1",arr4)
print("Array2",arr5)

Array1 [10 20 30 40]
Array2 [100 200 300 400]


In [33]:
cond=np.array([False,True,False,True])

In [36]:
#where can be used instead of complex nested if
# Returns arr4 for every true and arr5 for every false
res=np.where(cond,arr4,arr5)
print(res)

[100  20 300  40]


In [37]:
#Declare an array of random numbers
arr6=np.random.rand(7)

In [39]:
print("The original array",arr6)

The original array [0.21224942 0.05253094 0.93177356 0.5225464  0.05402898 0.41602931
 0.16618514]


In [40]:
print("Mean of the array\n")
print(arr6.mean())

Mean of the array

0.33647767800360157


In [41]:
print("Variance of the elements of array\n")
print(arr6.var())

Variance of the elements of array

0.0857374920225177


In [42]:
print("Standard Deviation of all the elements of array\n")
print(arr6.std())

Standard Deviation of all the elements of array

0.2928096515187259


In [43]:
print("Sum of all the elements of the array\n")
print(arr6.sum())

Sum of all the elements of the array

2.355343746025211


In [46]:
print("Sort the elements of the array\n")
arr6.sort()
print(arr6)

Sort the elements of the array

[0.05253094 0.05402898 0.16618514 0.21224942 0.41602931 0.5225464
 0.93177356]


In [47]:
arr7=np.array(['red','blue','white','red','white','black','blue'])
print("Original array",arr7)

Original array ['red' 'blue' 'white' 'red' 'white' 'black' 'blue']


In [48]:
print("Unique elements in the array\n")
print(np.unique(arr7))

Unique elements in the array

['black' 'blue' 'red' 'white']


#### Array loading and Saving
If we want to save the arrays for later use, the numpy functions of save() and load() can be used

In [49]:
print(arr6)

[0.05253094 0.05402898 0.16618514 0.21224942 0.41602931 0.5225464
 0.93177356]


In [50]:
np.save('saved_arr',arr6) #Saving array to saved_arr

In [51]:
arr8 = np.load('saved_arr.npy') #load the saved array from file
print("The array loaded from file",arr8) #print the array loaded from saved file

The array loaded from file [0.05253094 0.05402898 0.16618514 0.21224942 0.41602931 0.5225464
 0.93177356]


In [54]:
n1=np.arange(1,10,1).reshape(3,3)
print(n1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
n1[0].min()
n1[0].max()

3

In [61]:
n1.shape

(3, 3)

In [68]:
print(n1.shape[1])
print(n1.shape[0])

3
3


In [81]:
#Function to find the min max of each row in an array of random numbers and return the result as list
def getMinMax(ar):
    res=[]
    for i in range(ar.shape[0]):
        res.append(ar[i].min())
        res.append(ar[i].max())
    
    return res

In [70]:
ar=np.random.randint(1,100,size=(5,5))
print("The original array",ar)


The original array [[67 94 88 39 25]
 [83 41 96 19 80]
 [94 37 50 92 18]
 [86 99 36 31 69]
 [46 18 50 62 31]]


In [79]:
res_ar=getMinMax(ar)

In [80]:
print("The result MinMax list",res_ar)

The result MinMax list [25, 94, 19, 96, 18, 94, 31, 99, 18, 62]
